services:
  jekyll:
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling
    ports:
      - "4000:4000"
      - "35729:35729" # LiveReload용 포트
    volumes:
      - .:/usr/src/app
    environment:
      - JEKYLL_ENV=development